name: SimpleCommandDisabler
version: '1.0'
main: hu.nephesis.simpleCommandDisabler.Main
api-version: '1.21'
author: [Nephesiss]
description: Simple plugin to disable specific commands.
permissions:
  commanddisabler.bypass:
    description: Allows bypassing blocked commands.
    default: op
